- id: 19
  label: Labotix Multifibre
  delay: 0
  phase: 2
  quantity: 2
  servings: 19
  total_daily_quantity: 1
  total_daily_intakes_per_unit: 19
  pause_duration: 9
  posology_scheme:
    duration_value: 60
    day_time: evening
  intake:
    time_of_day: EVENING
    time_of_day_label: Soir
    unit_icon: templates_app/images/dosette.svg
    unit_label: Dosette
- id: 15
  label: Adrenex
  delay: 0
  phase: 2
  quantity: 2
  servings: 60
  total_daily_quantity: 2
  total_daily_intakes_per_unit: 30
  pause_duration: 0
  posology_scheme:
    duration_value: 60
    day_time: morning
  intake:
    time_of_day: MORNING
    time_of_day_label: Matin
    unit_icon: templates_app/images/capsules.svg
    unit_label: Gélule
- id: 3
  label: Labotix MB
  delay: 0
  phase: 1
  quantity: 2
  servings: 30
  total_daily_quantity: 1
  total_daily_intakes_per_unit: 30
  pause_duration: 0
  posology_scheme:
    duration_value: 60
    day_time: evening
  intake:
    time_of_day: EVENING
    time_of_day_label: Soir
    unit_icon: templates_app/images/drop.svg
    unit_label: Goutte
- id: 2
  label: Resveratrol
  delay: 0
  phase: 1
  quantity: 1
  servings: 60
  total_daily_quantity: 1
  total_daily_intakes_per_unit: 60
  pause_duration: 0
  posology_scheme:
    duration_value: 60
    day_time: mixed
  intake:
    time_of_day: MIXED
    time_of_day_label: Matin et soir
    unit_icon: templates_app/images/capsules.svg
    unit_label: Gélule
