# Generated by Django 5.2.7 on 2025-10-27 20:11

import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PosologySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Ex: 'Phase d'attaque', 'Phase d'entretien'", max_length=200, null=True, verbose_name='Nom du schéma')),
                ('order', models.PositiveIntegerField(default=1, help_text="Ordre d'affichage des schémas", verbose_name='Ordre')),
                ('duration_value', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Durée')),
                ('duration_type', models.CharField(choices=[('DAYS', 'Jour(s)'), ('WEEKS', 'Semaine(s)'), ('MONTHS', 'Mois'), ('CONTINUOUS', 'En continu')], default='DAYS', max_length=20, verbose_name='Unité de durée')),
                ('instructions', models.TextField(blank=True, help_text="Ex: 'Commencer par 1/2 pendant 15 jours'", null=True, verbose_name='Instructions spéciales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Schéma posologique',
                'verbose_name_plural': 'Schémas posologiques',
                'ordering': ['product', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Label')),
                ('posology_legacy', tinymce.models.HTMLField(blank=True, db_column='posology', default=None, null=True, verbose_name='Posologie (ancienne)')),
                ('duration', tinymce.models.HTMLField(blank=True, default=None, null=True, verbose_name='Durée')),
                ('price', models.FloatField(default=0, verbose_name='Prix')),
                ('phase', models.IntegerField(default=1, verbose_name='Phase (cortisol=1, microbiote=2)')),
                ('use_structured_posology', models.BooleanField(default=False, verbose_name='Utiliser la posologie structurée')),
            ],
            options={
                'verbose_name_plural': 'Produits',
            },
        ),
        migrations.CreateModel(
            name='PosologyIntake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=1, help_text='Ex: 1, 2, 0.5, 10', max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Quantité')),
                ('unit', models.CharField(choices=[('CAPSULE', 'Gélule(s)'), ('TABLET', 'Comprimé(s)'), ('ML', 'ml'), ('DROP', 'Goutte(s)'), ('DOSE', 'Dose(s)'), ('DOSETTE', 'Dosette(s)'), ('SACHET', 'Sachet(s)'), ('SPRAY', 'Spray(s)')], default='CAPSULE', max_length=20, verbose_name='Unité')),
                ('time_of_day', models.CharField(choices=[('MORNING', 'Matin'), ('NOON', 'Midi'), ('AFTERNOON', 'Après-midi'), ('EVENING', 'Soir'), ('BEDTIME', 'Au coucher'), ('ANYTIME', "N'importe quand")], max_length=20, verbose_name='Moment de la journée')),
                ('specific_time', models.TimeField(blank=True, help_text='Ex: 16:00', null=True, verbose_name='Heure spécifique')),
                ('intake_condition', models.CharField(choices=[('EMPTY_STOMACH', 'À jeun'), ('WITH_MEAL', 'Pendant le repas'), ('AFTER_MEAL', 'Après le repas'), ('BEFORE_MEAL', 'Avant le repas'), ('SPECIFIC_TIME', 'Heure spécifique'), ('NO_CONDITION', 'Aucune condition')], default='NO_CONDITION', max_length=20, verbose_name='Condition de prise')),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Nombre de fois par jour', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Fréquence par jour')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intakes', to='templates_app.posologyschedule', verbose_name='Schéma posologique')),
            ],
            options={
                'verbose_name': 'Prise posologique',
                'verbose_name_plural': 'Prises posologiques',
                'ordering': ['schedule', 'time_of_day', 'order'],
            },
        ),
        migrations.AddField(
            model_name='posologyschedule',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posology_schedules', to='templates_app.product', verbose_name='Produit'),
        ),
        migrations.CreateModel(
            name='PosologyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Date de modification')),
                ('change_description', models.TextField(verbose_name='Description du changement')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='Anciennes valeurs')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='Nouvelles valeurs')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='templates_app.posologyschedule', verbose_name='Schéma posologique')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posology_history', to='templates_app.product', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Historique posologique',
                'verbose_name_plural': 'Historiques posologiques',
                'ordering': ['-change_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='posologyschedule',
            unique_together={('product', 'order')},
        ),
    ]
