# Generated by Django 5.2.7 on 2025-11-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serving_unit',
            field=models.CharField(choices=[('CAPSULE', 'Gélule(s)'), ('TABLET', 'Comprimé(s)'), ('ML', 'ml'), ('DROP', 'Goutte(s)'), ('DOSE', 'Dose(s)'), ('DOSETTE', 'Dosette(s)'), ('SACHET', 'Sachet(s)'), ('SPRAY', 'Spray(s)')], default='CAPSULE', max_length=30, verbose_name='Unité de dosage'),
        ),
        migrations.AddField(
            model_name='product',
            name='servings_total',
            field=models.PositiveIntegerField(default=50, verbose_name='Nombre total de dose par produit'),
        ),
    ]
