# Generated by Django 5.2.7 on 2025-11-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_product_serving_unit_product_servings_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posologyintake',
            options={'ordering': ['scheme', 'time_of_day', 'order'], 'verbose_name': 'Prise posologique', 'verbose_name_plural': 'Prises posologiques'},
        ),
        migrations.RenameField(
            model_name='posologyintake',
            old_name='schedule',
            new_name='scheme',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='servings_total',
            new_name='servings',
        ),
        migrations.RemoveField(
            model_name='product',
            name='phase',
        ),
        migrations.AlterField(
            model_name='posologyintake',
            name='intake_condition',
            field=models.CharField(choices=[('AFTER_MEAL', 'Après le repas'), ('NO_CONDITION', 'Aucune condition')], default='NO_CONDITION', max_length=20, verbose_name='Condition de prise'),
        ),
        migrations.AlterField(
            model_name='posologyintake',
            name='time_of_day',
            field=models.CharField(choices=[('MORNING', 'Matin'), ('EVENING', 'Soir'), ('ANYTIME', "N'importe quand")], default='ANYTIME', max_length=20, verbose_name='Moment de la journée'),
        ),
    ]
