# Generated by Django 5.2.7 on 2025-11-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0003_alter_posologyintake_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='phase',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='posologyintake',
            name='intake_unit',
            field=models.CharField(choices=[('CAPSULE', 'Gélule'), ('TABLET', 'Comprimé'), ('ML', 'ml'), ('DROP', 'Goutte'), ('DOSE', 'Dose'), ('DOSETTE', 'Dosette'), ('SACHET', 'Sachet'), ('SPRAY', 'Spray')], default='CAPSULE', max_length=20, verbose_name='Unité'),
        ),
        migrations.AlterField(
            model_name='posologyintake',
            name='time_of_day',
            field=models.CharField(choices=[('MORNING', 'Matin'), ('EVENING', 'Soir'), ('MIXED', 'Matin et soir'), ('ANYTIME', "N'importe quand")], default='ANYTIME', max_length=20, verbose_name='Moment de la journée'),
        ),
        migrations.AlterField(
            model_name='product',
            name='serving_unit',
            field=models.CharField(choices=[('CAPSULE', 'Gélule'), ('TABLET', 'Comprimé'), ('ML', 'ml'), ('DROP', 'Goutte'), ('DOSE', 'Dose'), ('DOSETTE', 'Dosette'), ('SACHET', 'Sachet'), ('SPRAY', 'Spray')], default='CAPSULE', max_length=30, verbose_name='Unité de dosage'),
        ),
    ]
