# Generated by Django 5.2.7 on 2025-11-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0004_product_phase_alter_posologyintake_intake_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shopify_id',
            field=models.BigIntegerField(blank=True, default=None, null=True, verbose_name='Shopify Product ID'),
        ),
    ]
